repos:
- hooks:
  - id: black
    language_version: python3
  repo: https://github.com/psf/black
  rev: 22.12.0
- hooks:
  - id: flake8
    language_version: python3
  repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
