repos:
- hooks:
  - id: black
    language_version: python3
  repo: https://github.com/psf/black
  rev: 23.12.1
- hooks:
  - id: flake8
    language_version: python3
  repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
