on:
  push:
    branches:
      - main
  pull_request_target:

name: Tests

jobs:
  authorize:
    environment:
      ${{ (github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository) &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo âœ“
  test:
    needs: authorize
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-22.04, macos-11, windows-2019]
        pyv: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
      with:
        # NOTE: needed for pull_request_target to use PR code
        ref: ${{ github.event.pull_request.head.sha || github.ref }}

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.pyv }}

    - name: Install dependencies
      run: python -m pip install -e '.[fsspec, tests]'

    - name: Test
      run: python -m pytest -m "not manual"
      env:
        GDRIVE_USER_CREDENTIALS_DATA: ${{ secrets.GDRIVE_USER_CREDENTIALS_DATA }}
